name: macOs build

on:
  push:
    branches: [ master, develop, 0.9.* ]
    tags: 0.9.*
    
  pull_request:
    branches: [ master, develop, 0.9.* ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        qt: ['5.15.0']

    steps:
    - uses: actions/checkout@v2
      
    - name: Installing Qt framework
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}

    - name: Running qmake
      run:  cd $GITHUB_WORKSPACE; qmake pgmodeler.pro -r PREFIX=/Applications/pgModeler.app/Contents PGSQL_INC=`pg_config --includedir` PGSQL_LIB=`pg_config --libdir`/libpq.dylib CONFIG+=debug
    
    - name: Building pgModeler
      run: make -j6
     
    - name: Deploying pgModeler
      run: make install

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: /Applications/pgModeler.app
